"""Add OrderHistory table

Revision ID: 82e9bd6b678a
Revises: c0076288fc1d
Create Date: 2025-11-11 21:46:11.196933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e9bd6b678a'
down_revision: Union[str, Sequence[str], None] = 'c0076288fc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_history_order_id'), 'order_history', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_history_status'), 'order_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_history_status'), table_name='order_history')
    op.drop_index(op.f('ix_order_history_order_id'), table_name='order_history')
    op.drop_table('order_history')
    # ### end Alembic commands ###
