"""Add broadcast and reaction tables

Revision ID: c0076288fc1d
Revises: 
Create Date: 2025-11-11 19:47:20.154694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0076288fc1d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('photo_file_id', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_company_id'), 'broadcasts', ['company_id'], unique=False)
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.create_table('broadcast_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broadcast_id', 'client_id', name='_broadcast_client_reaction_uc')
    )
    op.create_index(op.f('ix_broadcast_reactions_reaction_type'), 'broadcast_reactions', ['reaction_type'], unique=False)
    op.drop_constraint(op.f('_telegram_chat_id_company_uc'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_telegram_chat_id'), 'clients', ['telegram_chat_id'], unique=False)
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'employees', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'expense_types', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'locations', 'companies', ['company_id'], ['id'])
    op.create_unique_constraint('_track_code_company_uc', 'orders', ['track_code', 'company_id'])
    op.create_index(op.f('ix_orders_location_id'), 'orders', ['location_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'roles', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'settings', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'shifts', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_location_id'), table_name='orders')
    op.drop_constraint('_track_code_company_uc', 'orders', type_='unique')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expense_types', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_index(op.f('ix_clients_telegram_chat_id'), table_name='clients')
    op.create_unique_constraint(op.f('_telegram_chat_id_company_uc'), 'clients', ['telegram_chat_id', 'company_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_broadcast_reactions_reaction_type'), table_name='broadcast_reactions')
    op.drop_table('broadcast_reactions')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_index(op.f('ix_broadcasts_company_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
